### ISSUE TITLE
Increase default UART buffer size

### ISSUE THREAD

**Issue by salkinium** [roboterclubaachen/xpcc#12]
Currently the default queue size is set to only a few bytes.
This makes sense on a small AVR, but not on larger AVRs and certainly not on ARM devices.

I would want to set the size by default to:
- 250 bytes for all the STM32 devices,
- 16 bytes for AVRs with <= 512B RAM, and
- 64 bytes for > 512B RAM.

**Comment by ekiwi** [comment]
While this does make xpcc look like a real memory hawk, I think it is the only possible way to keep the logger usable. Do you want to set the new device specific buffer size in the driver or in the device file?

**Comment by salkinium** [comment]
The IOStream in general requires a **lot** of memory and speed.

I would want to put 250B in the driver file for the Cortex-M and 64B in the driver file for AVRs and then overwrite the defaults for the ATtiny in the device file.

**Comment by salkinium** [comment]
There is also the problem that the `IODeviceWrapper` is non-blocking, so once the queue is full it will discard any new bytes.
There is a `IODeviceBlockingWrapper` which busy-waits until there is enough space in the queue.

**Comment by ekiwi** [comment]
> There is a IODeviceBlockingWrapper which busy-waits until there is enough space in the queue.

Haha, this is great. Probably exactly what @daniel-k was searching for last week. We definitely need to advertise this a little bit more!
But why then increase the default buffer? Now that we have user parameters, should we not switch back for the Uart to be non-buffered by default? In order to provide a minimal memory overhead in our default settings. If we did this we could change the parameters for the uart examples and maybe add a comment to the `main.cpp` file that tells the user, that the Uart is only buffered because of the parameter settings in `project.cfg`.

But thinking about this some more: if we do switch back to non-buffered by default we could indeed increase the default buffer size, since it would only take away space if the user chose to enable it.

**Comment by salkinium** [comment]
> Haha, this is great. Probably exactly what @daniel-k was searching for last week. We definitely need to advertise this a little bit more!

Then we should invert the behaviour to something like:
- IODeviceWrapper blocks, and
- IODeviceNonBlockingWrapper discards.

> In order to provide a minimal memory overhead in our default settings.

I don't think there is a shortage of memory on our devices, except on some small AVRs.
The issue has never manifolded itself before, since the `IODeviceWrapper` has _always_ busy-waited for a place in the UART queue, which sort-of defeats the UART queue especially when using it for an IOStream which conceptually transmits a lot of human readable ascii strings.

Specifically on the AVR more RAM is wasted by the fact that C-Strings need to be copied from Flash to RAM during boot, because of AVRs stupid memory addressing.
Perhaps using C++11 user-defined literals for creating C-Strings (something like `"string"_s`) stored in flash would be an option here to save RAM.
But loading from Flash takes 3 cycles compared to 1 cycle when loading from RAM.

I totally understand the technical desire to keep the memory footprint low.
However, I argue that there is more damage done by a CPU that is busy-waiting for the UART than "wasting" RAM, because
-  UART transmissions are reeeeaaaally slow (capped at 115.2kB by most USB-Serial dongles, or even less, if your clock does not allow a accurate high baudrate), so you can actually end up waiting for a long time, and
- You cannot easily "see" the wasted CPU cycles at runtime, but turning on a debug stream may now mess up your timings.

This issue is also about usability, because when I use the UART, its almost exclusively for piping my Logger as an IOStream though it.
And a "default" setting which requires the user to actively set a parameter in the `project.cfg` is **not** a default setting.
This is actually how it is implemented right now and it is always annoying, especially because the parameter implementation is not very usable itself either (it fails silently on wrong parameter names).

If you cannot spare the 16 (!) or 64 bytes for the Uart Tx queue, you might not want to use the IOStream in the first place.
Also there is no case you can argue against using 250B of Tx buffer by default on the STM32F4 with its ludicrous **192kB** of RAM, right?

There is also the problem, that a completely non-buffered (queue size=0) UART may have to be implemented differently. I think I saw this on the Xmega UART driver once.
Not sure if this is really something we want to do, since it completely messes with the UART peripheral interface.

We have to choose powerful defaults, and the fact that the current default of 8B annoy me as a developer, is not a good sign. The current situation is not a 90% solution, but premature optimization for perhaps one use-case (which one actually?).

**Comment by ekiwi** [comment]
> This issue is also about usability, because when I use the UART, its almost exclusively for piping my Logger as an IOStream though it.

OK. I just had a look at the Arduino Library and they allocate some bytes for a Uart Buffer by default as well:

`hardware/arduino/cores/arduino/HardwareSerial.cpp:56`

``` .cpp
#if (RAMEND < 1000)
  #define SERIAL_BUFFER_SIZE 16
#else
  #define SERIAL_BUFFER_SIZE 64
#endif
```

So I guess `xpcc` won't look bad if we do the same thing.

> Then we should invert the behaviour to something like:
> -  IODeviceWrapper blocks, and
> - IODeviceNonBlockingWrapper discards.

I like this idea, because while for use in production, you would rather discard messages than to change the execution speed of your program, during prototyping (which is what `xpcc` is generally used for), a lot of times, you would want to see all messages, even if this means that your program might be halted. This behavior would be consistent with the way `Arduino` handles a full buffer and thus might be the behavior that is expected by most people.

`hardware/arduino/cores/arduino/HardwareSerial.cpp:464`

``` .cpp
  // If the output buffer is full, there's nothing for it other than to 
  // wait for the interrupt handler to empty it a bit
  // ???: return 0 here instead?
  while (i == _tx_buffer->tail)
    ;
```

However, we should not change the behavior of existing code without a warning. Therefore I would like to propose a second template argument for the `IODeviceWrapper` class of the following type:

``` .cpp
enum class
BufferFull  // or BufferFullBehavior
{
    Block,
    Discard,
};
```

Now existing code will stop to compile, because there is one template argument of type `BufferFull` missing, people will look at this new enum class and make a conscious decision on how to handle a full buffer.

**Comment by salkinium** [comment]
> However, we should not change the behavior of existing code without a warning. Therefore I would like to propose a second template argument for the IODeviceWrapper class of the following type:
> 
> enum class
> BufferFull  // or BufferFullBehavior
> {
>     Block,
>     Discard,
> };
> Now existing code will stop to compile, because there is one template argument of type BufferFull missing, people will look at this new enum class and make a conscious decision on how to handle a full buffer.
> 
> The second template argument is accepted.

If I understand correctly, you want the `IODeviceWrapper` to be blocking by default?
Does that mean `Block` as a default template argument for the `BufferFull` type?
That would kind of negate the effect of consciously deciding the behavior.

So I would be in favor of explicitly having to add the `BufferFull` argument.

**Comment by ekiwi** [comment]
> So I would be in favor of explicitly having to add the `BufferFull` argument.

Yes that is what I meant by saying

> Now existing code will stop to compile, because there is one template argument of type BufferFull missing

Thus there is no default, but the user will need to specify how `IODeviceWrapper` is supposed to behave.

**Comment by salkinium** [comment]
Ok. I like this solution very much.

![Excellent](http://www.reactiongifs.com/r/exc.gif).

**Comment by salkinium** [comment]
So right now a Wrapper has to be instantiated like this:

```
xpcc::IODeviceWrapper< Uart, xpcc::IOBufferBehavior::Discard > device;
```

or

```
xpcc::IODeviceWrapper< Uart, xpcc::IOBufferBehavior::BusyWait > device;
```

Is that acceptable?

**Comment by ekiwi** [comment]
Personally I'd prefer if we could fit the word `Full` somewhere in there as this behavior only  becomes relevant as soon as the buffer is full. Maybe `IOBufferFullBehavior`? Or is this too long.
Anyway, thank you very much for fixing this issue!

**Comment by salkinium** [comment]
Hm, the length is the most annoying to me.
Here are two that are still shorter than `xpcc::IODevice::BufferBehavior::Discard`:

What about `xpcc::IOBuffer::BlockIfFull` and `xpcc::IOBuffer::DiscardIfFull`?
(`*WhenFull` or `*OnFull`).

Or `xpcc::IOBufferFull::Block` and `xpcc::IOBufferFull::Discard`.

**Comment by ekiwi** [comment]
I like `xpcc::IOBuffer::DiscardIfFull` and `xpcc::IOBuffer::BlockIfFull`.

**Comment by salkinium** [comment]
Accepted and implemented.
