### ISSUE TITLE
use F_CPU to initialize xpcc::clock::fcpu_MHz and xpcc::clock::fcpu_kHz

### ISSUE THREAD

**Issue by ekiwi** [roboterclubaachen/xpcc#58]
`F_CPU` is generated from the clock setting in the `project.cfg`.
Is there any reason not to use this value, to initialize `xpcc::clock::fcpu_MHz` and `xpcc::clock::fcpu_kHz`?

**Comment by salkinium** [comment]
I wanted to purge `F_CPU` (and `clock` in the `project.cfg`), since it's declaration is redundant and error prone.
The `SystemClock` class knows the final CPU speed best and writes that information into the global variables.

I know that the 8MHz is not always accurate, ie. some STM32 come with a 16MHz internal clock, but `F_CPU` has the wrong semantics to use it like that.

**Comment by ekiwi** [comment]
Don't we need to inject the CPU frequency for AVR microcontrollers?

**Comment by salkinium** [comment]
Yes, of course only remove `clock` and `F_CPU` for Cortex-M devices (and perhaps Xmega devices).

(It might be possible to do some tricks though to get the same SystemClock interface for AVRs working, which only generates the Fuse Bit Values and places them inside a specific linker section.
This could then be interpreted by the toolchain to flash it automagically with avrdude.)
